In [118]:
import numpy as np
#from numpy.linalg import matrix_power

A = np.matrix(
    [[1, 1],
     [1, 1]])
B = np.matrix(
    [[4, 1], 
     [2, 2]])

# C = A B array([[6,3],[6,3]]) on a 6=1*4+1*2, 3=1*1+1*2, 6=1*4+1*2 3= 1*1+1*2
C0 = np.matmul(A, B)    ;print(C0)     
C1 = A * B              ;print(C1)  #meme resultat avec l'operateur *

A80 = matrix_power(A, 8) ;print(A8)  #ne pas utiliser np.power c est correct
A81 = A**8             ;print(A81)   #meme resultat avec l'operateur **

[[6 3]
 [6 3]]
[[6 3]
 [6 3]]
[[128 128]
 [128 128]]
[[128 128]
 [128 128]]


In [82]:
A = np.matrix(
    [[0.1,0.2,0.7],
     [0.3,0.4,0.3],
     [0.5,0.4,0.1]])              ;print("A   = ",A)
AT = A.transpose()                ;print("AT  = ", AT)                          
V = np.matrix([1,0,0])            ;print("V   = ",V)
VT = V.transpose()                ;print("VT  = ",VT)

AVT = A * V.transpose()           ;print("AVT = ",AVT)
VAT = V * A.transpose()           ;print("VAT = ",VAT,  "  AVT.T = ", AVT.transpose())

n =3
H0 = np.dot(V, (A**n).transpose())            ;print("H0  = ",H)
K0 = np.dot(A**n ,V.transpose()).transpose()  ;print("K0  = ",K) #meme resultat

H1 = (V * (A**n).transpose())                  ;print("H1  = ",H0)
K1 = (A**n * V.transpose()).transpose()        ;print("K1  = ",K0)

A   =  [[0.1 0.2 0.7]
 [0.3 0.4 0.3]
 [0.5 0.4 0.1]]
AT  =  [[0.1 0.3 0.5]
 [0.2 0.4 0.4]
 [0.7 0.3 0.1]]
V   =  [[1 0 0]]
VT  =  [[1]
 [0]
 [0]]
AVT =  [[0.1]
 [0.3]
 [0.5]]
VAT =  [[0.1 0.3 0.5]]   AVT.T =  [[0.1 0.3 0.5]]
H0  =  [[0.256 0.312 0.352]]
K0  =  [[0.256 0.312 0.352]]
H1  =  [[0.256 0.312 0.352]]
K1  =  [[0.256 0.312 0.352]]


In [156]:
MC_pi_n = lambda P, pi0, n : np.dot(pi0, np.linalg.matrix_power(P,n))  
MC_pi_n = lambda P, pi0, n : (pi0 * P**n) 
MCT_pi_n = lambda P, pi0, n : (P**n * pi0.transpose()).transpose() 

In [119]:
#exepmle 01 CM01
P = np.matrix(
    [[0.1,0.2,0.7],
     [0.3,0.4,0.3],
     [0.5,0.4,0.1]]) 
pi0 = A = np.matrix([[0.1,0.2,0.7]])
n = 2
pi2= MC_pi_n(P,pi0,n)         ;print(pi2)

[[0.256 0.316 0.428]]


In [120]:
#exemple 02 CM02
#https://en.wikipedia.org/wiki/Examples_of_Markov_chains
P = np.matrix(
    [[0.9,0.1],
     [0.5,0.5]]) 
pi0 = A = np.matrix([1,0])
n = 2
pi2= MC_pi_n(P,pi0,n)         ;print(pi2)

[[0.86 0.14]]


In [157]:
#exemple 02 CM02
#trouver sur http://aix1.uottawa.ca/~jkhoury/markov.htm
P = np.matrix(
    [[0, 0.5, 0.5],
     [0.25, 0.5, 0.25],
     [0.25, 0.25, 0.5],]) 

PT = np.matrix(
    [[0, 0.25, 0.25],
     [0.5, 0.5, 0.25],
     [0.5, 0.25, 0.5],]) 

pi0 = np.matrix([1,0,0])
n = 7

pi_n= MCT_pi_n(PT, pi0,n)         ;print("pi_",n, " = ",pi_n,"")
pi_n= MC_pi_n(P,pi0,n)            ;print("pi_",n, " = ",pi_n,"")

print("P",n," = ",P**n)

#for i in range(1,20):  
#    P_n = P**i  
    #print("P",i," = ",P_n)
#    pi_n= MC_pi_n(P,pi0,i)         ;print("pi_",i, " = ",pi_n,"")   

pi_ 7  =  [[0.19995117 0.40002441 0.40002441]] 
pi_ 7  =  [[0.19995117 0.40002441 0.40002441]] 
P 7  =  [[0.19995117 0.40002441 0.40002441]
 [0.20001221 0.40002441 0.39996338]
 [0.20001221 0.39996338 0.40002441]]


In [127]:
T = np.matrix([[1,0,0],[0,1,0],[0,0,1]])                ;print(T)
U = np.matrix([[1,1,1],[1,1,1],[1,1,1]])                ;print(T)
U = np.matrix([[1,1],[1,1]])                ;print(T)
T = U
n = 4
G = np.power(T,n)          ;print(" G  = ", G)
K = T**n          ;print("K = ",K)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
 G  =  [[1 1]
 [1 1]]
K =  [[8 8]
 [8 8]]


matrix([[1, 2],
        [3, 4]])

matrix([[1, 3],
        [2, 4]])

In [33]:
V

matrix([[1, 2]])

In [37]:
(V * A.transpose()).transpose()

matrix([[ 5],
        [11]])

In [38]:
A * V.transpose()

matrix([[ 5],
        [11]])

In [21]:
U = np.matrix([1,2])
V.transpose() * A

matrix([[1, 2],
        [2, 4]])

In [22]:
U.transpose()

matrix([[1],
        [2]])

In [23]:
U = V.transpose()

In [24]:
U

matrix([[1],
        [2]])

In [28]:
A.transpose()

matrix([[1],
        [2]])

In [66]:
#i = np.array([[1, 1,1], [1,1,1], [1,1,1]]) # matrix equiv. of the imaginary unit
#md = np.matrix([[1, 1,1], [1,1,1], [1,1,1]]) # matrix equiv. of the imaginary unit
#md = np.matrix([[1, 1], [1,1]]) # matrix equiv. of the imaginary unit
#mx = matrix_power(a, 8) # should = -i array([[ 0, -1],       [ 1,  0]])
#print(mx)
#print((md**8))

<!--- <b>Etat periodique</b>
- <b>Classe periodqique</b>
- <b>Probabilité d'absorption</b>
- <b>Temps du premier passage</b>
- <b>Temps de retour moyen</b-->