# Chaine de Markov
#### Slimane mohamed
#### TP MEPS Master I ISIA 

- $j$ est <b>accessible</b> à partir de $i$ (noté $i \to j$) $\implies$ $\exists n >0,  P^{(n)}_{ij} > 0$
- $i$ et $j$ sont <b>communiquantes</b> $\implies$ $i \to j \text{ & } j \to i$
- <b>Classe transitoire</b> : il est possible d'en sortir sans pouvoir plus jamais y revenir
- <b>Classe recurrente</b> : il est impossible de la quitter
- <b>Etat absorbant</b> : tout seul forme une classe recurrente.
- <b>CM irreductible</b> : constituée d'une seule classe et qui est recurrente.
- <b>Distribution limite</b> : est la distribution $\pi$ verifiant $\pi_j = \lim_{n \to \infty} P^{(n)}_{ij}$ c.a.d ($\pi = \lim_{n \rightarrow \infty} \pi^{(n)}$)
- <b>Distribution Stationnaire</b> : est la distribution $\pi$ verifiant $\pi \times \textbf{P} = \pi$ c.a.d ($\pi (\textbf{P}-I)=\textbf{0}$)<br>

In [7]:
import numpy as np
from numpy.linalg import matrix_power

A = np.matrix(
    [[1, 1],
     [1, 1]])

B = np.matrix(
    [[4, 1], 
     [2, 2]])

C0 =  A * B
C0= np.matmul(A,B)
print(C0)

print(B**3)

[[6 3]
 [6 3]]
[[84 30]
 [60 24]]


In [8]:
# C = A B array([[6,3],[6,3]]) 
# on a 6=1*4+1*2, 3=1*1+1*2, 6=1*4+1*2 3= 1*1+1*2
C0 = np.matmul(A, B)       ;print(C0)     
C1 = A * B                 ;print(C1)  #meme resultat avec l'operateur *

A80 = matrix_power(A, 8)   ;print(A80)  #ne pas utiliser np.power c est pas correct
A81 = A**8                 ;print(A81)   #meme resultat avec l'operateur **

[[6 3]
 [6 3]]
[[6 3]
 [6 3]]
[[128 128]
 [128 128]]
[[128 128]
 [128 128]]


### Distribution de n ieme etape

En donnant $\pi(0)$ et la matrice de transition $P$, on peut calculer la distribution de CM à étape $n$ avec la relation :

$$
\pi(n) =  \pi(0) . P^n 
$$


In [11]:
# MC_pi_n  = lambda P, pi0, n : np.dot(pi0, np.linalg.matrix_power(P,n))  
# ou plus simplement 

MC_pi_n  = lambda P, pi0, n : (pi0 * P**n) #sans faire de transposer votre collegue avait raison

\begin{align*}
    \pi^{(0)} & = \left[ 1 \quad  0 \right]\\
    \textbf{P} &= \left[
    \begin{array}{rrr}
      0.9 & 0.1\\
      0.5  & 0.5
    \end{array}
  \right]\\
  \pi^{(1)} = \pi^{(0)} . \textbf{P} &= \left[ 1 \quad  0 \right]
  \left[
    \begin{array}{rrr}
      0.9 & 0.1\\
      0.5  & 0.5
    \end{array}
  \right]
  = \left[ 0.9 \quad  0.1 \right]
\end{align*}

<img src="images/exo001.png"/>

In [15]:
#exemple 001 CM01
#https://en.wikipedia.org/wiki/Examples_of_Markov_chains
CM01_P = np.matrix(
    [[0.9,0.1],
     [0.5,0.5]]) 


CM01_pi0 = np.matrix([1,0])

MC_pi_n(CM01_P, CM01_pi0, 1)

matrix([[0.9, 0.1]])

In [3]:
import numpy as np
CDF = np.matrix.cumsum(CM01_P, axis=1)
print(CDF[0])
np.argmax(CDF[0] > 0.95)

[[0.9 1. ]]


1

In [16]:
import random

S =['S','R']  #P =np.matrix([0,1]) X = CM01_pi0 * P.transpose() S[X.tolist()[0][0]] #d_c =  np.matrix([0.3,0.7])
d_c =  np.matrix([1,0])  #CDF = np.matrix.cumsum(CM01_P, axis=1)

def getState(pi_c):
    xv = random.uniform(0, 1)
    pi_cc = np.cumsum(pi_c)
    idx = np.argmax(pi_cc > xv)
    return idx

#

import time
def generateMC(States,pi_c,P,n):
    MC= ""
    for i in range(n):
        idx = getState(pi_c)
        ch = States[idx]   #print(xv,"    ", d_cc, "   ",idx, "  ", d_cc.tolist()[0][idx], "    ", (d_cc < xv))
        pi_c =  pi_c * P      #d_cc = np.cumsum(d_c)
        time.sleep(1)
        print(ch, end= "")  
        MC += ch
    return MC

MC = generateMC(S, d_c, CM01_P, 100)
        
#print(MC)
    

SRSSSSSSSSSSSSRSSSSSSSSSSSSSSRRSSSSSSSSSSSSSSSSSSRSSSSSSRSSSRSSRRSSSSSSSSSRRSSSRSSSRSSSRSRSSSSSSSRSS

In [5]:


alist= [0.5, 0.3, 0.9, 0.8]
[ n for n,i in enumerate(alist) if i>0.9 ]

[]

In [6]:
CM01_n = 1
pi1= MC_pi_n(CM01_P,CM01_pi0,CM01_n)         ;print(pi1.tolist()[0])
# [0.9, 0.1]

[0.5, 0.5]


\begin{align*}
  \pi^{(2)} = \pi^{(1)} . \textbf{P} = \pi^{(0)} . \textbf{P}^2 &= \left[ 1 \quad  0 \right]
  \left[
    \begin{array}{rrr}
      0.9 & 0.1\\
      0.5  & 0.5
    \end{array}
  \right]^2
  = \left[ 0.86 \quad  0.14 \right]
\end{align*}

In [10]:
#exemple 02 CM02
#https://en.wikipedia.org/wiki/Examples_of_Markov_chains
CM02_P = np.matrix(
    [[0.9,0.1],
     [0.5,0.5]]) 
CM02_pi0 = np.matrix([1,0])
CM02_n = 2
pi1= MC_pi_n(CM02_P,CM02_pi0,CM02_n)         ;print(pi1.tolist()[0])
#[0.8600000000000001, 0.14]

[0.8600000000000001, 0.14]


\begin{align*}
    \pi^{(0)} & = \left[ 1/3 \quad  1/3 \quad 1/3 \right]\\
    \textbf{P} &= \left[
    \begin{array}{rrr}
      0.3 & 0.3 & 0.4\\
      0.4  & 0.4 & 0.2 \\
      0.5 & 0.3 & 0.2
    \end{array}
  \right]\\
  \pi^{(1)} = \pi^{(0)} . \textbf{P} &= \left[ 1/3 \quad  1/3 \quad 1/3 \right]
  \left[
    \begin{array}{rrr}
      0.3 & 0.3 & 0.4\\
      0.4  & 0.4 & 0.2 \\
      0.5 & 0.3 & 0.2
    \end{array}
  \right]
  = \left[ 0.4000 \quad  0.3333 \quad 0.2666 \right]
\end{align*}

In [11]:
#exemple 03 CM03
#trouver sur http://aix1.uottawa.ca/~jkhoury/markov.htm

CM03_P = np.matrix(
    [[0.3, 0.3, 0.4],
     [0.4, 0.4, 0.2],
     [0.5, 0.3, 0.2],]) 
CM03_pi0 = np.matrix([1/3,1/3,1/3])
CM03_n = 1
n=10
pi_n= MC_pi_n(CM03_P,CM03_pi0,CM03_n)            ;print("pi_",n, " = ",pi_n,"")
# pi_ 1  =  [[0.4        0.33333333 0.26666667]] 

pi_ 10  =  [[0.4        0.33333333 0.26666667]] 


\begin{align*}
    \pi^{(0)} & = \left[ 1 \quad  0 \quad 0 \right]\\
    \textbf{P} &= \left[
    \begin{array}{rrr}
      0 & 0.5 & 0.5\\
      0.25  & 0.5 & 0.25 \\
      0.25 & 0.25 & 0.5
    \end{array}
  \right]\\
  \pi^{(1)} = \pi^{(0)} . \textbf{P} &= \left[ 1/3 \quad  1/3 \quad 1/3 \right]
  \left[
    \begin{array}{rrr}
      0 & 0.5 & 0.5\\
      0.25  & 0.5 & 0.25 \\
      0.25 & 0.25 & 0.5
    \end{array}
  \right]
  = \left[ 0.19995117 \quad 0.40002441 \quad 0.40002441 \right]
\end{align*}

In [12]:
#exemple 04

CM04_P = np.matrix(
    [[0, 0.5, 0.5],
     [0.25, 0.5, 0.25],
     [0.25, 0.25, 0.5],]) 
CM04_pi0 = np.matrix([1,0,0])
CM04_n = 7
n=5
pi_n= MC_pi_n(CM04_P,CM04_pi0,CM04_n)            ;print("pi_",n, " = ",pi_n,"")
# pi_ 7  =  [[0.19995117 0.40002441 0.40002441]] 

pi_ 5  =  [[0.19995117 0.40002441 0.40002441]] 


In [18]:
# j accessible de i dans au plus n etapes
#estAccessible = 
def acc(i,j, P, n) : 
    Q = P
    for k in range(n):
        if Q[i,j]>0: return k, Q[i,j]
        Q = Q * P
    return -1, 0

CM04_P = np.matrix(
    [[0, 0.5, 0.5],
     [0.5, 0.5, 0],
     [0.25, 0.25, 0.5],]) 

acc(1,2,CM04_P, 10)
print(CM04_P**2)

[[0.375 0.375 0.25 ]
 [0.25  0.5   0.25 ]
 [0.25  0.375 0.375]]


In [24]:
# j accessible de i dans au plus n etapes
#estAccessible = 
CM04_P = np.matrix(
    [[0, 0.5, 0.5],
     [0.5, 0.5, 0],
     [0.25, 0.25, 0.5],]) 

def com(i,j, P, n) : 
    r0, p0 = acc(i,j, P, n)
    if r0 == -1: return -1, 0
    r1, p1 = acc(j,i, P, n)
    if r1 == -1: return -1, 0
    return r0*r1, r0, p0, r1, p1 

def getClassComofState(i, P, n):
    result = [i]
    
    for j in range(P.shape[0]):
        #rint(j)
        if j != i:
            cc = com(i,j,P,n)
            if cc != -1:
                result.append(j)
    return result

print(getClassComofState(0,CM04_P,1000))

CM04_P**5



getCC(P,n):
    for i in range(P.shape[0]):
        if not isVisited[i]:
            ci = getClassComofState(i,P,n);
            rs.append(ci)
            #marquer les etats dans cette etape

[0, 1, 2]


matrix([[0.28125   , 0.4296875 , 0.2890625 ],
        [0.2890625 , 0.4296875 , 0.28125   ],
        [0.28515625, 0.42578125, 0.2890625 ]])

In [14]:
    
CM04_P = np.matrix(
    [[0, 0.5, 0.5],
     [0.5, 0.5, 0],
     [0.25, 0.25, 0.5],]) 

com(1,2,CM04_P, 10)

In [14]:
P= np.matrix(
    [[1/2,    1/2,  0.0, 0.0, 0.0, 0.0],
     [0.0,    0.0,  1.0, 0.0, 0.0, 0.0],
     [1/3,    0.0,  0.0, 1/3, 1/3, 0.0],
     [0.0,    0.0,  0.0, 1/2, 1/2, 0.0],
     [0.0,    0.0,  0.0, 0.0, 0.0, 1.0],
     [0.0,    0.0,  0.0, 0.0, 1.0, 0.0],] )

(0, 1, 0.25, 0, 0.25)

In [ ]:
cc = {}
states = {1,2}
ss ={1,2}

while len(ss)>0:
    

ss = {1,2,2}
len(ss)


    
    

In [8]:
CM04_P

NameError: name 'CM04_P' is not defined

In [ ]:
#import numpy as np
C = np.zeros(CM04_P.shape)

P= np.matrix(
    [[0, 0.5, 0.5],
     [0.5, 0.5, 0],
     [0.25, 0.25, 0.5],]) 


ed = False 
i = 0
n = 10
while i < n:
    for i in range(P.shape[0]):
        for j in range(P.shape[1]):
            if P[i,j]>0:
                C[i,j]=1    
    #print(i)
    i=i+1
C

In [28]:
P= np.matrix(
    [[0, 0.5, 0.5],
     [0.5, 0.5, 0],
     [0.25, 0.25, 0.5],]) 

cc  = P.shape[1]
cc

s = {0,1,2}

#cc ={0:{0,1},1:{2}}

cc ={0:{0,1,2}}

c=[0,0,0]

nb_c = 1

#
for i in range(P.shape[0]):
    for j in range(P.shape[1]):
        if j>i:
            if (not j in cc[c[i]]):
                if P[i,j] >0 and P[j,i] > 0: 
                    cc[c[i]].add(j)
                    cc[c[j]].remove(j)
                    c[j]=c[i]
                    print(i,"   ", j,"    ",P[i,j], "    ",cc)
                

In [83]:
import numpy as np
P= np.matrix(
    [[0,    0.5,  0.5],
     [0.5,  0.5,  0  ],
     [0.25, 0.25, 0.5],])

P= np.matrix(
    [[0.6,    0.2,  0.0, 0.2, 0.0],
     [0.6,    0.4,  0.0, 0.0, 0.0],
     [0.0,    0.3,  0.2, 0.3, 0.2],
     [0.3,    0.0,  0.0, 0.7, 0.0],
     [0.0,    0.0,  0.4, 0.0, 0.6]] )

P= np.matrix(
    [[1/2,    1/2,  0.0, 0.0, 0.0, 0.0],
     [0.0,    0.0,  1.0, 0.0, 0.0, 0.0],
     [1/3,    0.0,  0.0, 1/3, 1/3, 0.0],
     [0.0,    0.0,  0.0, 1/2, 1/2, 0.0],
     [0.0,    0.0,  0.0, 0.0, 0.0, 1.0],
     [0.0,    0.0,  0.0, 0.0, 1.0, 0.0],] )

s = 0
cs00 = dict()
n= 10

P0 = P
for k in range(n):
    c =  np.ones(P.shape[0])*(-1)
    csold = cs00
    cs00 = dict()
    #print(c)
    for i in range(P.shape[0]):
        if c[i]==-1:
            cs00[i]= set([i])
            c[i]=i
            for j in range(i+1,P.shape[0]):
                if(P[i,j]>0 and P[j,i]>0) and not (j in cs00):
                    c[j]=i
                    cs00[i].add(j)
                    #print(i,"   ",cs00)
    print(k,"   ",cs00)
    print(P)
    Pold = P
    P = P0 * P
    #print(np.array_equal(P,Pold))
    #print(P==Pold)
            
  

    
        

In [130]:
P= np.matrix(
    [[1/2,    1/2,  0.0, 0.0, 0.0, 0.0],
     [0.0,    0.0,  1.0, 0.0, 0.0, 0.0],
     [1/3,    0.0,  0.0, 1/3, 1/3, 0.0],
     [0.0,    0.0,  0.0, 1/2, 1/2, 0.0],
     [0.0,    0.0,  0.0, 0.0, 0.0, 1.0],
     [0.0,    0.0,  0.0, 0.0, 1.0, 0.0],] ) 


P= np.matrix(
    [[0.6,    0.2,  0.0, 0.2, 0.0],
     [0.6,    0.4,  0.0, 0.0, 0.0],
     [0.0,    0.3,  0.2, 0.3, 0.2],
     [0.3,    0.0,  0.0, 0.7, 0.0],
     [0.0,    0.0,  0.4, 0.0, 0.6]] )

Q = np.zeros(P.shape)
P0 = P
n = 10
for k in range(1,n):
    Qold = Q.copy()
    for i in range(P.shape[0]):
        for j in range(P.shape[1]):
            if(i !=j and P[i,j]>0 and Q[i,j]==0): Q[i,j]=k
    P = P0 * P
print(Q)

[[0. 1. 0. 1. 0.]
 [1. 0. 0. 2. 0.]
 [2. 1. 0. 1. 1.]
 [1. 2. 0. 0. 0.]
 [3. 2. 1. 2. 0.]]


In [131]:
cs00 = dict()
c =  np.ones(Q.shape[0])*(-1)
for i in range(Q.shape[0]):
    if c[i]==-1:
        cs00[i]= set([i])
        c[i]=i
        for j in range(Q.shape[1]):
            if j > i :
                if(Q[i,j]>0 and Q[j,i]>0) and not (j in cs00):
                    c[j]=i
                    cs00[i].add(j)
    print(i,"   ",cs00)

0     {0: {0, 1, 3}}
1     {0: {0, 1, 3}}
2     {0: {0, 1, 3}, 2: {2, 4}}
3     {0: {0, 1, 3}, 2: {2, 4}}
4     {0: {0, 1, 3}, 2: {2, 4}}
